name: Build Branch

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build and publish to build branch
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js 20
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Cache node modules
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: v1-npm-${{ hashFiles('package.json') }}
          restore-keys: v1-npm-

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - run: |
          mkdir -p out
          cp -r dist lib excel.js index.ts index.d.ts package.json README.md out/

      - name: Publish to build branch
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          BRANCH: build
          FOLDER: out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
